name: needle_orm_example
description: A complete example for Needle Orm (another ORM in dart world).
version: 0.1.0
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  logging: ^1.0.2
  mysql1: ^0.20.0
  pool: ^1.5.0
  postgres: ^2.4.1
  postgres_pool: ^2.1.3
  needle_orm: ^0.1.0
  needle_orm_mariadb: ^0.1.0
  needle_orm_postgres: ^0.1.0
  needle_orm_migration_generator: ^0.1.0
  needle_orm_migration: ^0.1.0
  needle_orm_migration_runner: ^0.1.0
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
  needle_orm_generator: ^0.1.0