publish_to: none
name: needle_orm_minerva_example
description: Minerva application.
version: 0.1.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  logging: ^1.1.0
  minerva: ^0.2.6
  mysql1: ^0.20.0
  needle_orm: ^0.1.0
  needle_orm_mariadb: ^0.1.0
  needle_orm_postgres: ^0.1.0
  needle_orm_migration: ^0.1.0
  needle_orm_migration_runner: ^0.1.0
  postgres_pool: ^2.1.4
  stack_trace: ^1.11.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dio: ^4.0.6
  build_runner: ^2.0.0
  needle_orm_generator: ^0.1.0
  needle_orm_migration_generator: ^0.1.0
