publish_to: none
name: needle_orm_minerva_example
description: Minerva application.
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  minerva: ^0.2.6
  needle_orm: ^0.0.6
  needle_orm_mariadb: ^0.0.6
  needle_orm_postgres: ^0.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dio: ^4.0.6
  build_runner: ^2.0.0
  needle_orm_generator: ^0.0.6