name: needle_orm

repository: https://github.com/needle-dart/needle_orm_all.dart

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true
    
scripts:
  get:
    exec: dart pub get .
  test:
    exec: dart test .
  analyze:
    exec: dart analyze .
  format:
    exec: dart format .
  generate:
    exec: dart run build_runner build
    select-package:
      depends-on: build_runner

  doc:
    exec: dart doc
  doc-clean:
    exec: rm -rf doc

