builders:
  needle_orm_generator:
    import: "package:needle_orm_generator/needle_orm_generator.dart"
    builder_factories: ["ormGenerator"]
    build_extensions: { ".dart": ["orm.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
