name: needle_orm_generator
description: Generate all orm helper classes for needle-orm.
version: 0.0.4
homepage: https://github.com/needle-dart/needle_orm_all.dart
repository: https://github.com/needle-dart/needle_orm_all.dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=2.0.0 <4.2.0"
  build: ^2.0.0
  build_config: ^1.0.0
  code_builder: ^4.0.0
  source_gen: ^1.0.0
  logging: ^1.0.2
  needle_orm: ^0.0.4
dev_dependencies:
  build_runner: ^2.0.0
  test: ^1.5.3
  mysql1: ^0.19.0
  pool: ^1.5.0
  postgres: ^2.4.1
  postgres_pool: ^2.1.3
  needle_orm_mariadb: ^0.0.4
  needle_orm_postgres: ^0.0.4