name: needle_orm_migration
description: ORM migration for Needle ORM, and ORM framework inspired by Ebean.io (an excellent ORM from Java/Kotlin world).
version: 0.0.4+1
homepage: https://github.com/needle-dart/needle-orm-all
repository: https://github.com/needle-dart/needle-orm-all.git

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  inflection3: ^0.5.3+2
  recase: ^4.0.0
  logging: ^1.0.2
  needle_orm: ^0.0.4+1
  analyzer: ^4.0.0
  source_gen: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.5

