name: needle_orm_migration_runner
description: ORM migration for Needle ORM, and ORM framework inspired by Ebean.io (an excellent ORM from Java/Kotlin world).
version: 0.0.6
homepage: https://github.com/needle-dart/needle-orm-all
repository: https://github.com/needle-dart/needle-orm-all.git

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  needle_orm_migration: 0.0.6
  needle_orm: 0.0.6
  args: ^2.1.0
  charcode: ^1.2.0
  postgres: ^2.4.0
  mysql_client: ^0.0.24
  mysql1: ^0.20.0
  logging: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
