name: needle_orm_mariadb
description: ORM for dart. This package supports MariaDB/MySQL (using mysql1).
version: 0.1.1
homepage: https://github.com/needle-dart/needle-orm-all
repository: https://github.com/needle-dart/needle-orm-all.git

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  mysql1: ^0.20.0
  logging: ^1.0.2
  needle_orm: ^0.1.1
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
