name: needle_orm_postgres
description: postgres support for needle_orm
version: 0.0.5
homepage: https://github.com/needle-dart/needle-orm-all
repository: https://github.com/needle-dart/needle-orm-all.git

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  pool: ^1.5.0
  postgres: ^2.4.1
  postgres_pool: ^2.1.3
  logging: ^1.0.2
  #   path: ^1.8.0
  needle_orm: ^0.0.5
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
