builders:
  needle_orm_migration_generator:
    import: "package:needle_orm_migration_generator/needle_orm_migration_generator.dart"
    builder_factories: ["ormMigrationGenerator"]
    build_extensions: { ".dart": [".mig.dart"] }
    auto_apply: dependents
    build_to: source